//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_ST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        public int Department_id { get; set; }
        public string Department_Name { get; set; }
    
        public virtual Departments Departments1 { get; set; }
        public virtual Departments Departments2 { get; set; }
        public virtual Departments Departments11 { get; set; }
        public virtual Departments Departments3 { get; set; }
    }
}
