//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_ST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public int Reception_id { get; set; }
        public int Personnal_id { get; set; }
        public Nullable<int> Department_id { get; set; }
        public Nullable<int> Post_id { get; set; }
        public Nullable<System.DateTime> Reception_Date { get; set; }
        public Nullable<System.DateTime> Dismissal_Date { get; set; }
        public string Status { get; set; }
    
        public virtual Destination Destination1 { get; set; }
        public virtual Destination Destination2 { get; set; }
        public virtual State State { get; set; }
    }
}
