//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_ST
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class St_E : DbContext
    {
        private static St_E _context;

        public St_E()
            : base("name=St_E")
        {
        }
        public static St_E GetContext()
        {
            if (_context == null)
                _context = new St_E();

            return _context;
        }

    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Destination> Destination { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<State> State { get; set; }
    }
}
