//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_ST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Personnal_id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Middle_Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public string Phone { get; set; }
        public string Education { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    }
}
